"""Cross-machine baseline check for the determinant-basis FCI solver.

Validates that ``iDEA.methods.interacting_det.solve`` reproduces the same
energy and density as the committed baselines (generated by the labelled
``iDEA.methods.interacting.solve`` for uu_80 and uud_60, and by the
determinant solver itself for uudd_30 which the labelled solver can't
reliably produce).
"""

import importlib.util
from pathlib import Path

import numpy as np
import pytest

import iDEA.methods.interacting_det as det


REPO_ROOT = Path(__file__).resolve().parents[1]
BASELINE_DIR = REPO_ROOT / "benchmarks" / "interacting_baseline"


def _load_benchmark_module():
    path = REPO_ROOT / "benchmarks" / "benchmark_interacting.py"
    spec = importlib.util.spec_from_file_location("benchmark_interacting", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.mark.parametrize(
    "case_name",
    ["interacting_uu_80", "interacting_uud_60", "interacting_uudd_30"],
)
def test_determinant_solver_matches_baseline(case_name):
    baseline_path = BASELINE_DIR / f"{case_name}.npz"
    if not baseline_path.exists():
        pytest.skip(
            f"baseline missing: {baseline_path}. "
            f"Generate with: python benchmarks/benchmark_interacting.py generate"
        )

    benchmark = _load_benchmark_module()
    factory = benchmark.CASES.get(case_name)
    if factory is None:
        pytest.skip(f"case factory missing for {case_name}")
    s = factory()

    state = det.solve(s, k=0)
    density = det.density(s, state)

    with np.load(baseline_path, allow_pickle=False) as baseline:
        ref_energy = float(baseline["energy"])
        ref_density = baseline["density"]

    assert np.isclose(float(state.energy), ref_energy, rtol=1e-10, atol=1e-12), (
        f"energy: current={float(state.energy):.16e} "
        f"baseline={ref_energy:.16e} "
        f"diff={abs(float(state.energy) - ref_energy):.6e}"
    )
    assert np.allclose(density, ref_density, rtol=1e-10, atol=1e-12), (
        f"density: max_abs_diff={float(np.max(np.abs(density - ref_density))):.6e}"
    )


def test_determinant_solver_density_integrates_to_electron_count():
    benchmark = _load_benchmark_module()
    s = benchmark.CASES["interacting_uu_80"]()
    state = det.solve(s, k=0)
    n = det.density(s, state)
    integral = float(np.sum(n) * s.dx)
    assert abs(integral - s.count) < 1e-10, (
        f"density should integrate to electron count {s.count}, got {integral}"
    )
