"""Cross-machine baseline check + Phase B sanity tests for the
determinant-basis FCI solver.

Validates that ``iDEA.methods.interacting_det.solve`` reproduces the same
energy and density as the committed baselines (generated by the labelled
``iDEA.methods.interacting.solve`` for uu_80 and uud_60, and by the
determinant solver itself for uudd_30 which the labelled solver can't
reliably produce).

Adds Phase B+ sanity tests per the expert friend's request:
  - Random-vector Hermiticity check of the LinearOperator
  - Eigenpair residual norm ``||H psi - E psi||``
  - Dense exact cross-check against the labelled Hamiltonian at toy N=6
    across u, ud, uu, uud, uudd
"""

import contextlib
import importlib.util
import io
from pathlib import Path

import numpy as np
import pytest

import iDEA
import iDEA.interactions
import iDEA.methods.interacting
import iDEA.methods.interacting_det as det
import iDEA.system


REPO_ROOT = Path(__file__).resolve().parents[1]
BASELINE_DIR = REPO_ROOT / "benchmarks" / "interacting_baseline"


def _load_benchmark_module():
    path = REPO_ROOT / "benchmarks" / "benchmark_interacting.py"
    spec = importlib.util.spec_from_file_location("benchmark_interacting", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.mark.parametrize(
    "case_name",
    ["interacting_uu_80", "interacting_uud_60", "interacting_uudd_30"],
)
def test_determinant_solver_matches_baseline(case_name):
    baseline_path = BASELINE_DIR / f"{case_name}.npz"
    if not baseline_path.exists():
        pytest.skip(
            f"baseline missing: {baseline_path}. "
            f"Generate with: python benchmarks/benchmark_interacting.py generate"
        )

    benchmark = _load_benchmark_module()
    factory = benchmark.CASES.get(case_name)
    if factory is None:
        pytest.skip(f"case factory missing for {case_name}")
    s = factory()

    state = det.solve(s, k=0)
    density = det.density(s, state)

    with np.load(baseline_path, allow_pickle=False) as baseline:
        ref_energy = float(baseline["energy"])
        ref_density = baseline["density"]

    assert np.isclose(float(state.energy), ref_energy, rtol=1e-10, atol=1e-12), (
        f"energy: current={float(state.energy):.16e} "
        f"baseline={ref_energy:.16e} "
        f"diff={abs(float(state.energy) - ref_energy):.6e}"
    )
    assert np.allclose(density, ref_density, rtol=1e-10, atol=1e-12), (
        f"density: max_abs_diff={float(np.max(np.abs(density - ref_density))):.6e}"
    )


def test_determinant_solver_density_integrates_to_electron_count():
    benchmark = _load_benchmark_module()
    s = benchmark.CASES["interacting_uu_80"]()
    state = det.solve(s, k=0)
    n = det.density(s, state)
    integral = float(np.sum(n) * s.dx)
    assert abs(integral - s.count) < 1e-10, (
        f"density should integrate to electron count {s.count}, got {integral}"
    )


# ---------------------------------------------------------------------------
# Phase B+ sanity tests
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("case_name", ["interacting_uu_80", "interacting_uud_60"])
def test_determinant_linear_operator_is_hermitian(case_name):
    """Friend-requested check: <x, H y> == <H x, y> for random vectors."""
    benchmark = _load_benchmark_module()
    s = benchmark.CASES[case_name]()
    comps = det._build_solver_components(s)
    rng = np.random.default_rng(seed=0)
    op = comps.op
    for _ in range(5):
        x = rng.standard_normal(comps.D)
        y = rng.standard_normal(comps.D)
        lhs = float(np.dot(x, op @ y))
        rhs = float(np.dot(op @ x, y))
        assert np.isclose(lhs, rhs, rtol=1e-10, atol=1e-12), (
            f"{case_name}: <x,Hy>={lhs:.16e} <Hx,y>={rhs:.16e} "
            f"diff={abs(lhs - rhs):.6e}"
        )


@pytest.mark.parametrize("case_name", ["interacting_uu_80", "interacting_uud_60"])
def test_determinant_residual_norm_below_tolerance(case_name):
    """Friend-requested check: ||H psi - E psi|| / ||psi|| small for the solved eigenpair."""
    benchmark = _load_benchmark_module()
    s = benchmark.CASES[case_name]()
    state = det.solve(s, k=0)
    comps = det._build_solver_components(s)
    psi = state.det_amplitudes.ravel()
    Hpsi = comps.op @ psi
    residual = np.linalg.norm(Hpsi - state.energy * psi) / np.linalg.norm(psi)
    assert residual < 1e-8, f"{case_name}: residual norm {residual:.6e} > 1e-8"


def _project_to_physical_subspace(psi_flat, electrons, n_grid):
    """Apply same-spin Young antisymmetrizer per channel.

    For the m<=2 case (all our test electron strings), the projector
    factorises into pairwise antisymmetrizations P_- = (I - swap)/2 along
    each same-spin axis pair. Returns the projected vector with the same
    shape as the input.
    """
    n_e = len(electrons)
    psi = np.asarray(psi_flat).reshape((n_grid,) * n_e)

    up_axes = [i for i, e in enumerate(electrons) if e == "u"]
    down_axes = [i for i, e in enumerate(electrons) if e == "d"]

    for axes in (up_axes, down_axes):
        m = len(axes)
        if m < 2:
            continue
        if m == 2:
            psi = (psi - np.swapaxes(psi, axes[0], axes[1])) / 2
        else:
            raise NotImplementedError(
                f"physical projector not implemented for m={m} same-spin electrons"
            )
    return psi.ravel()


@pytest.mark.parametrize("electrons", ["u", "ud", "uu", "uud", "uudd"])
def test_determinant_matches_dense_full_solve(electrons):
    """Friend-requested check: cross-validate against dense labelled diagonalisation.

    Builds the labelled-basis Hamiltonian via the existing iDEA solver,
    dense-diagonalises with numpy.linalg.eigh, projects each eigenvector
    onto the same-spin-antisymmetric subspace, takes the lowest eigenvalue
    whose projection is nonzero (the physical ground state), and compares
    that against the determinant solver's energy.
    """
    n = 6
    x = np.linspace(-4.0, 4.0, n)
    v_ext = 0.5 * 0.5**2 * x**2
    v_int = iDEA.interactions.softened_interaction(x)
    s = iDEA.system.System(x, v_ext, v_int, electrons=electrons)

    state_det = det.solve(s, k=0)

    H_sparse = iDEA.methods.interacting.hamiltonian(s)
    H_dense = H_sparse.toarray() if hasattr(H_sparse, "toarray") else np.asarray(H_sparse)
    energies, eigvecs = np.linalg.eigh(H_dense)

    ref_energy = None
    for idx in range(len(energies)):
        projected = _project_to_physical_subspace(eigvecs[:, idx], electrons, n)
        if np.linalg.norm(projected) > 1e-6:
            ref_energy = float(energies[idx])
            break

    assert ref_energy is not None, (
        f"no antisymmetric eigenvalue found in dense spectrum for electrons={electrons}"
    )
    assert np.isclose(state_det.energy, ref_energy, rtol=1e-10, atol=1e-12), (
        f"electrons={electrons} N={n}: "
        f"det={state_det.energy:.16e} "
        f"dense_antisym={ref_energy:.16e} "
        f"diff={abs(state_det.energy - ref_energy):.6e}"
    )
